### ISSUE TITLE
NuGet Package Release

### ISSUE THREAD

**Issue by SunshineSpring666** [sebarslan/Maui.NullableDateTimePicker#1]
Hi [sebarslan](https://github.com/sebarslan),
    Great job on DateTimePicker control!
    Could you please release a NuGet Package, so that people can download it by NuGet Package Manager? Thanks.

    Best Regards
    Joe

**Comment by sebarslan** [comment]
Hi @SunshineSpring666 ,
Thank you for your nice words.
When Control works stable, I will make a package as soon as possible.

Best Regards

**Comment by sebarslan** [comment]
Nuget package created.

Best Regards

**Comment by SunshineSpring666** [comment]
Thanks a lot!
