### ISSUE TITLE
Windows : Application Hangs on changing month

### ISSUE THREAD

**Issue by hardikphd** [sebarslan/Maui.NullableDateTimePicker#10]
When we try to change month either by using left/right arrow or by clicking on current month and selecting different month, does not work on Windows.

Issue is reproducible on sample application "Maui.NullableDateTimePicker.Samples.Net8"
I am using 2.0 version of Maui.NullableDateTimePicker Nuget

Here is the screen, App hangs and we can't do anything

<img width="153" alt="235bf001-61c5-47ba-9122-2e7ffbec1abb" src="https://github.com/sebarslan/Maui.NullableDateTimePicker/assets/16522825/99a1112f-d60d-4bcc-8141-caa9d121511a">

Here is the first use case,I am using, month selections screen
https://github.com/sebarslan/Maui.NullableDateTimePicker/assets/16522825/35294f29-8b4c-4ee9-9e7e-4deeff3d5ac5

In second usecase,  where I am using left/right arrow
https://github.com/sebarslan/Maui.NullableDateTimePicker/assets/16522825/bea28b40-af57-4562-a245-9e842488749c

Issue comes from "Application.Current.Dispatcher.DispatchAsync", which is called from BuildCalendar function via "SafeInvokeOnMainThreadAsync"
`      internal static async Task SafeInvokeOnMainThreadAsync(Action action)
    {
        if (DeviceInfo.Platform == DevicePlatform.WinUI)
        {
            await Application.Current.Dispatcher.DispatchAsync(action);
        }
        else
        {
            await MainThread.InvokeOnMainThreadAsync(action);
        }
    }
`

I tried commenting out if clause, It worked without issue
`    internal static async Task SafeInvokeOnMainThreadAsync(Action action)
    {
        //if (DeviceInfo.Platform == DevicePlatform.WinUI)
        //{
        //    await Application.Current.Dispatcher.DispatchAsync(action);
        //}
        //else
        {
            await MainThread.InvokeOnMainThreadAsync(action);
        }
    }
`

Can you look at this issue please?

**Comment by sebarslan** [comment]
Hi @hardikphd 
Thank you for reporting this error. 
I fixed the bug and will create a new version as soon as possible.
Best Regards

**Comment by JeremyBP** [comment]
Same here, let us know when the new version is live on nuget.
Thanks for your work :)

**Comment by sebarslan** [comment]
Hi @JeremyBP and @hardikphd 
The new version has been uploaded.

Thanks and best regards
