### ISSUE TITLE
Change color of days in calendar

### ISSUE THREAD

**Issue by Lompzx** [sebarslan/Maui.NullableDateTimePicker#18]
How i can change color of days in calendar ?
I tryed DayStyle target Label but doesn't work.
I want it to stay fixed so it isn't affected by the device's theme

**Comment by sebarslan** [comment]
Hello @Lompzx 
please use 'Button' as target.
Best regards

**Comment by Lompzx** [comment]
> Hello @Lompzx please use 'Button' as target. Best regards

It worked, thanks
