### ISSUE TITLE
Windows: Calendar popup does not work with NullableDateTimePicker on ContentPage that is accessed via PushModalAsync

### ISSUE THREAD

**Issue by SonicScholar** [sebarslan/Maui.NullableDateTimePicker#19]
Request to reopen #4 

Relevant comment from linked issue.
https://github.com/sebarslan/Maui.NullableDateTimePicker/issues/4#issuecomment-2337604942

**Comment by SonicScholar** [comment]
Do you have any thoughts? Perhaps I or someone at my company could take a look at this issue if there are any good spots to update. I spent a little time looking at the community toolkit popup code that is referenced.

Not sure if the bug is in this repo or in theirs.

**Comment by sebarslan** [comment]
Hi @SonicScholar 

The Communitytoolkit popup works when I try it on a modal page and with a content page on Windows. There is probably something in my code that prevents it from working in the modal. I will try to solve this as soon as possible.

Best Regards

**Comment by sebarslan** [comment]
Hi @SonicScholar 

With Community Toolkit version 9.1.0, the problem of opening a popup in a modal window in Windows has been resolved. I also upgraded the version to 9.1.0. You can test it.

Best Regards
