### ISSUE TITLE
Question: How to change the placeholder color

### ISSUE THREAD

**Issue by vhugogarcia** [sebarslan/Maui.NullableDateTimePicker#20]
Hello friends,

First, I would like to thank you @sebarslan for creating this great MAUI plugin. I just love it.

However, I have one question, is it possible to change the placeholder color? I tried the property PlaceholderColor without luck.

Thanks in advance

**Comment by sebarslan** [comment]
Hello @vhugogarcia 

You can change the placeholder color as follows.

Add the NullableDateTimePicker-Namespace control to your Styles.xaml  file and  assign the placeholder color for the entry.

<ResourceDictionary 
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:ndtp="clr-namespace:Maui.NullableDateTimePicker;assembly=Maui.NullableDateTimePicker">
     
     ......
     <Style TargetType="ndtp:NullableDateTimePickerEntry">
        <Setter Property="PlaceholderColor" Value="{AppThemeBinding Light={StaticResource Black}, Dark={StaticResource PrimaryDarkText}}" />
    </Style>
</ResourceDictionary>

Best Regards
