### ISSUE TITLE
Question: How to not set any icons?

### ISSUE THREAD

**Issue by OudomMunint** [sebarslan/Maui.NullableDateTimePicker#21]
Currently All Icons I use are not scaled properly, I want to not set any at all but if I remove Icon property it sets it to the default calendar icon.

**Comment by sebarslan** [comment]
Hi @OudomMunint 

For example, try adding a blank image that is 1x1 pixel in size.

**Comment by OudomMunint** [comment]
Okay I will try that, is it possible to create a style class to target the NDTP so i can set the blank image globally? Thanks!

**Comment by sebarslan** [comment]
Yes, you can create a style as follows:

<Style TargetType="ndtp:NullableDateTimePicker">
    <Setter Property="Icon" Value="1x1.png" />
</Style>


I will also add a property named HideIcon in version 2.3.2.

Best Regards

**Comment by OudomMunint** [comment]
> Yes, you can create a style as follows:
> 
> `<Style TargetType="ndtp:NullableDateTimePicker"> <Setter Property="Icon" Value="1x1.png" /> </Style> `
> 
> I will also add a property named HideIcon in version 2.3.2.
> 
> Best Regards

Thanks for your hard work! I'll give those a shot 👍

**Comment by sebarslan** [comment]
Hi @OudomMunint 
in the new version a ptoperty has been added to hide the icon.
Best Regards

**Comment by OudomMunint** [comment]
> Hi @OudomMunint in the new version a ptoperty has been added to hide the icon. Best Regards

Thanks I've just checked it out, works well so far! thanks a lot, cheers 🍻
