### ISSUE TITLE
Question : How can I add automation Id when loading the popup using a command

### ISSUE THREAD

**Issue by mshenoy83** [sebarslan/Maui.NullableDateTimePicker#23]
First of all great control, much love. We're changed all out calendar controls to yours. We are using a command to invoke 
`await NullableDateTimePicker.OpenCalendarAsync(NullableDatePickerOptions);`
We're conducting some automation testing and the testers have mentioned that they are unable to get any hooks. This is what they are saying

```
Android Calendar control has been changed/updated, and new one controller doesn't have hooks (resource-id, etc) for auto scripting.  Previous one had those hooks, so would be really great if we can have those back in the future.

This is applicable for all date field related calendar controllers 


Some of the previous resource-id were:

@resource-id='android:id/date_picker_header_year
@resource-id='android:id/prev  
@resource-id='android:id/next
@resource-id='android:id/button1' and @text='OK'

```

**Comment by mshenoy83** [comment]
I could maybe add a PR for this?

**Comment by sebarslan** [comment]
Hi @mshenoy83 

Is this AutomationId needed for the popup? Can I add it to return a result?

**Comment by mshenoy83** [comment]
Thank you for responding. We need an automation id for the 
- move next and previous buttons
- Ok and Cancel Buttons
- For the the year list

**Comment by sebarslan** [comment]
Ok, I'll add this

**Comment by sebarslan** [comment]
Hi @mshenoy83 

I added the automationId. Could you please test it if possible? 

Thanks.

**Comment by mshenoy83** [comment]
Sure will do

**Comment by mshenoy83** [comment]
All the automation ids are coming up thank you.  I only just realised after testing that we would also need automation ids for the day buttons. Apologise, should have raised this earlier. Would you please be able to add that too?

<img width="866" alt="image" src="https://github.com/user-attachments/assets/49359344-ee1b-4ef6-9652-4b7333426389" />

**Comment by sebarslan** [comment]
Automationid added for days.

Best Regards

**Comment by mshenoy83** [comment]
I can see a possible issue here.Since the automation id is based on the day string. There could be 2 buttons with the same day like 1. Could you change that to be options.automationid_calendardaybutton_month_day

**Comment by sebarslan** [comment]
Yes, you are absolutely right, thank you for this warning. I also added the month.

**Comment by mshenoy83** [comment]
Thank you. The automation ids are coming up. Eagerly awaiting the next release. Do you have any approximate timeline for it?
<img width="919" alt="image (1)" src="https://github.com/user-attachments/assets/bf8aacad-3891-41df-a78d-3df24d8d9372" />

**Comment by sebarslan** [comment]
I want to use a listview instead of a picker for years and months. 
You can access the year listview in the same way via "AutomationId_YearsSelectList". 
Can you check if this is ok for you? 
I will create a new version when I finish this new Listview.
Thanks and Best Regards
