### ISSUE TITLE
.NET 9.0 Support

### ISSUE THREAD

**Issue by Orgbrat** [sebarslan/Maui.NullableDateTimePicker#24]
I have a MAUI project that I use this nuget package in and I am trying to migrate my solution from .NET 8.0 to .NET 9.0.

When I try to build my solution I get the PRI errors below. I have updated all nugets to latest including CommunityToolkit.Maui to 10.0.0 but still would not build without errors. I have determined that it is this control causing the issue.  Removed your nuget and commented all code referencing it.  The solution now builds and runs with no issues.

WINAPPSDKGENERATEPROJECTPRIFILE : error : PRI175: 0x80073b0f - Processing Resources failed with error: Duplicate Entry.

WINAPPSDKGENERATEPROJECTPRIFILE : error : PRI277: 0x80073b0f - Conflicting values for resource 'Files/Microsoft.Maui/Platform/Windows/Styles/WindowRootViewStyle.xbf'

So can you say when your package will be  .NET 9.0 compatible?

**Comment by sebarslan** [comment]
Hi @Orgbrat 

I will upload version 2.4.0 which supports .net 9.0 as soon as possible.

Best Regards

**Comment by sebarslan** [comment]
.net 9 support added
