### ISSUE TITLE
Margin Problem

### ISSUE THREAD

**Issue by SE250880** [sebarslan/Maui.NullableDateTimePicker#3]
Hi [sebarslan](https://github.com/sebarslan),

thanks for that control. It works very well. 
I have only one problem with margin in iOS. I put two Nullabledatepicker-Controls next to each other and set the marginproperty. But I think the marginvalue is ignored? Maybe it´s a Maui bug?

**Comment by sebarslan** [comment]
Hi @SE250880,
thank you for your nice words.
You can now assign a margin value.
Kind regards
