### ISSUE TITLE
Calendar popup does not work with NullableDateTimePicker on ContentPage that is accessed via PushModalAsync

### ISSUE THREAD

**Issue by DwightM66** [sebarslan/Maui.NullableDateTimePicker#4]
To reproduce using Maui.NullableDateTimePicker.Samples:
  - Add a new content page called NewPage.xaml
  - Add a NullableDateTimePicker to this page
  - modify MainPage.xaml.cs and change OnCounterClicked content to: 
`await Navigation.PushModalAsync(new NewPage());`

 - Run the app and click the "Click Me" button
 - Clicking the calendar icon on the NewPage NullableDateTimePicker  will result in a blank page opening instead of the calendar popup

- This was tested on Windows 11

**Comment by sebarslan** [comment]
Hello,
Can you try something like this?
await Navigation.PushAsync(new NewPage());

I'll check why this doesn't work with PushModalasync.

Kind regards

**Comment by DwightM66** [comment]
This now works with PushModalAsync?

**Comment by sebarslan** [comment]
Hi @DwightM66 

CommunityToolkit-Popup developers have fixed this problem.
Popup now works on the page opened with pushmodalasync.
NullableDateTimePicker can now also be used this way.

Best Regards

**Comment by SonicScholar** [comment]
Hello, super cool project you've got here and thanks for sharing with the Maui community.

Using the Maui.NullableDateTimePicker.Samples.Net8 project, I don't see this issue as being resolved.
The project (as is) on the main branch- When I click the button that calls Navigation.PushModalAsync(new NewPage())

I can't get the picker to display on that page. I didn't update any packages or anything.

![image](https://github.com/user-attachments/assets/e6377822-ce49-4f14-8e3f-f65f6fea54fd)

So is this issue resolved, err?

**Comment by sebarslan** [comment]
Hello @SonicScholar,

First of all, thank you for your compliments.
Normally, a popup opens in a modal, but I think there is a problem with Windows caused by me.
I will try to fix this problem and then I will let you know.

Best regards
