### ISSUE TITLE
Need a NullableDateTimePickerPopup without the entry.

### ISSUE THREAD

**Issue by ImGonaRot** [sebarslan/Maui.NullableDateTimePicker#5]
We have custom entry controls that we use in our application with specific styles such as rounded borders.
The current NullableDateTimePicker control does not allow users to call the underlying NullableDateTimePickerPopup since it is marked as internal class.
We could like to use our own custom formatted entry boxes but call the NullableDateTimePickerPopup from a tap event on our custom entry control.
Can someone make the popup portion of the NullableDateTimePicker public for outsider callers to use it?

**Comment by sebarslan** [comment]
Hello,
Thank you for your suggestion.
I will add this as soon as possible.
