### ISSUE TITLE
Error ShowPopupAsync 

### ISSUE THREAD

**Issue by SE250880** [sebarslan/Maui.NullableDateTimePicker#7]
Hi,

before your nuget was released I only used your dll in .net7 and arrange 2 datetimecontrols next to each other and this worked well. 

Now, i have installed your nuget and use your control on iOS 17 (.net 8) and nothing happend by clicking the button.

In the debugwindow there is an exception: System.MissingMethodException: Method not found: System.Threading.Tasks.Task`1<object> CommunityToolkit.Maui.Views.PopupExtensions.ShowPopupAsync<!0>(Microsoft.Maui.Controls.Page,!!0)

Am I doing something wrong?

**Comment by sebarslan** [comment]
Hi @SE250880,
After trying and running it with Net 8.0, I will release the 1.2.1 version.
Are you using the new version of CommunityToolkit.Maui in your own project? I will test accordingly.
King Regards

**Comment by SE250880** [comment]
Hi @sebarslan,
thanks for your help. Yes, I have updated all to the newest versions.
King Regards

**Comment by sebarslan** [comment]
Hi @SE250880 ,
I made it compatible with .net 8.0. Can you test it and give me feedback? I will release the new version.

Thanks.

**Comment by sebarslan** [comment]
Hi @SE250880

Thank you very much for the test.
You can give padding values from the top and bottom without affecting the text appearance.
If necessary, a property called IconHeight can be added in the future.

Best Regards

**Comment by imuller** [comment]
@sebarslan Hi, when will the 1.2.1 be released?

**Comment by sebarslan** [comment]
Hi @SE250880 
I will release it in a few hours
Regards

**Comment by SE250880** [comment]
Hi @sebarslan 

thanks for 2.0.0.  It works, but I still have a warning in the output window. Can you help me?

Microsoft.Maui.Controls.Element: Warning: Maui.NullableDateTimePicker.NullableDateTimePickerContent is already a child of Microsoft.Maui.Controls.ContentPage. Remove Maui.NullableDateTimePicker.NullableDateTimePickerContent from Microsoft.Maui.Controls.ContentPage before adding to Maui.NullableDateTimePicker.NullableDateTimePickerPopup.

**Comment by sebarslan** [comment]
Hi @SE250880 
What exactly are you doing and on which platform are you receiving this warning? Can you give me an example?
Thanks a lot

**Comment by SE250880** [comment]
I installed your version 2.0 in VS 2022. The app is implemented in .Net8 ios 17.
I use your control in a contentpage like this:
![grafik](https://github.com/sebarslan/Maui.NullableDateTimePicker/assets/34155651/4d1003c1-1490-4fa6-804a-5a9d3859cc6c)
Then I start the app in the debugger and when I choose a date with your control, the popup window is closed and the warning appears in the output window from VS.

**Comment by sebarslan** [comment]
Hi @SE250880 
Thanks very much for the example. I will fix this problem in the next version.
I wish you a nice day.

**Comment by imuller** [comment]
@sebarslan When will the next version get released?

**Comment by sebarslan** [comment]
I don't know yet. But I will try to upload it soon.
Normally you can use it this way. Since this is a warning, we can ignore it for now :)
Have a nice day

**Comment by sebarslan** [comment]
fixed

**Comment by sebarslan** [comment]
Hi @imuller,
The new version has been uploaded.

Best regards
