### ISSUE TITLE
Update documentation for Entry with TapGestureRecognizer

### ISSUE THREAD

**Issue by imuller** [sebarslan/Maui.NullableDateTimePicker#8]
When the property "IsReadOnly" is enabled, the TapGestureRecognizer won't work.

**Comment by sebarslan** [comment]
Hi @imuller 
Entry is already readonly.
In version 2.0.0, I will make only the icon clickable again.
Or do you want to prevent clicking on the Icon with IsReadonly?
King Regards

**Comment by imuller** [comment]
I mean that the documentation shows that the Entry is readonly. But there is also a TapGestureRecognizer on the Entry. When I was implementing this, the Entry did nothing. After removing the "IsReadOnly" the TapGestureRecognizer works :)

I only mention it so that other users don't think the NullableDateTimePicker aint working.

**Comment by sebarslan** [comment]
Hi @imuller ,
I understand, normally Calendar is displayed when you click on the icon. From now on, I think it seems more logical to open it only with the icon.
Thanks

**Comment by sebarslan** [comment]
Thank you very much for warning me. Now I open the calendar with just the icon :)
I wish you a nice day.
